name: fitboxing_app
description: A new Flutter project

publish_to: 'none' # Remove this line if you're planning to publish

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"  # Add this line to specify the SDK version constraint

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.0  # You can adjust this version if needed
  http: ^1.2.2
  intl: ^0.20.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.2
  flutter_animated_icons: ^1.0.0 # Added the flutter_animated_icons dependency

  # Add other dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
